apiVersion: apps/v1
kind: Deployment
metadata:
  name: swarm-queen
  namespace: swarm-intelligence
  labels:
    app: swarm-queen
    agent-type: queen
    priority: "10"
spec:
  replicas: 1  # Only one Queen agent
  selector:
    matchLabels:
      app: swarm-queen
  template:
    metadata:
      labels:
        app: swarm-queen
        agent-type: queen
    spec:
      containers:
      - name: queen-agent
        image: <ACR_LOGIN_SERVER>/swarm-queen:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: AGENT_TYPE
          value: "queen"
        - name: AGENT_PRIORITY
          value: "10"
        - name: MAX_INSTANCES
          value: "1"
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: swarm-secrets
              key: anthropic-api-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: swarm-secrets
              key: openai-api-key
        - name: PERPLEXITY_API_KEY
          valueFrom:
            secretKeyRef:
              name: swarm-secrets
              key: perplexity-api-key
        - name: AZURE_COSMOS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: swarm-secrets
              key: cosmos-endpoint
        - name: AZURE_COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: swarm-secrets
              key: cosmos-key
        - name: AZURE_SERVICE_BUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: swarm-secrets
              key: servicebus-connection
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: swarm-queen-service
  namespace: swarm-intelligence
spec:
  selector:
    app: swarm-queen
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP