version: '3.8'

services:
  # Queen Agent - Master Coordinator
  swarm-queen:
    build:
      context: ../
      dockerfile: azure-deploy/Dockerfile.queen
    container_name: swarm-queen
    environment:
      - AGENT_TYPE=queen
      - AGENT_PRIORITY=10
      - MAX_INSTANCES=1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - AI_PLATFORM_URL=http://host.docker.internal:8000
      - ENABLE_SWARM_INTELLIGENCE=true
      - ENABLE_DISTRIBUTED_MEMORY=true
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - swarm-memory:/app/data
    networks:
      - swarm-network
    restart: unless-stopped

  # Architect Agent
  swarm-architect:
    build:
      context: ../
      dockerfile: azure-deploy/Dockerfile.worker
      args:
        AGENT_TYPE: architect
        AGENT_PRIORITY: 8
        MAX_INSTANCES: 2
    container_name: swarm-architect
    environment:
      - AGENT_TYPE=architect
      - AGENT_PRIORITY=8
      - MAX_INSTANCES=2
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - QUEEN_URL=http://swarm-queen:8080
    depends_on:
      - swarm-queen
    networks:
      - swarm-network
    restart: unless-stopped

  # Coder Agent
  swarm-coder:
    build:
      context: ../
      dockerfile: azure-deploy/Dockerfile.worker
      args:
        AGENT_TYPE: coder
        AGENT_PRIORITY: 7
        MAX_INSTANCES: 3
    container_name: swarm-coder
    environment:
      - AGENT_TYPE=coder
      - AGENT_PRIORITY=7
      - MAX_INSTANCES=3
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - QUEEN_URL=http://swarm-queen:8080
    depends_on:
      - swarm-queen
    networks:
      - swarm-network
    restart: unless-stopped
    deploy:
      replicas: 2

  # Tester Agent
  swarm-tester:
    build:
      context: ../
      dockerfile: azure-deploy/Dockerfile.worker
      args:
        AGENT_TYPE: tester
        AGENT_PRIORITY: 6
        MAX_INSTANCES: 2
    container_name: swarm-tester
    environment:
      - AGENT_TYPE=tester
      - AGENT_PRIORITY=6
      - MAX_INSTANCES=2
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - QUEEN_URL=http://swarm-queen:8080
    depends_on:
      - swarm-queen
    networks:
      - swarm-network
    restart: unless-stopped

  # Researcher Agent
  swarm-researcher:
    build:
      context: ../
      dockerfile: azure-deploy/Dockerfile.worker
      args:
        AGENT_TYPE: researcher
        AGENT_PRIORITY: 5
        MAX_INSTANCES: 2
    container_name: swarm-researcher
    environment:
      - AGENT_TYPE=researcher
      - AGENT_PRIORITY=5
      - MAX_INSTANCES=2
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - QUEEN_URL=http://swarm-queen:8080
    depends_on:
      - swarm-queen
    networks:
      - swarm-network
    restart: unless-stopped

  # Security Agent
  swarm-security:
    build:
      context: ../
      dockerfile: azure-deploy/Dockerfile.worker
      args:
        AGENT_TYPE: security
        AGENT_PRIORITY: 9
        MAX_INSTANCES: 1
    container_name: swarm-security
    environment:
      - AGENT_TYPE=security
      - AGENT_PRIORITY=9
      - MAX_INSTANCES=1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - QUEEN_URL=http://swarm-queen:8080
    depends_on:
      - swarm-queen
    networks:
      - swarm-network
    restart: unless-stopped

  # Local SQLite Database (for local testing)
  swarm-db:
    image: nouchka/sqlite3:latest
    container_name: swarm-db
    volumes:
      - swarm-memory:/root/db
    networks:
      - swarm-network
    command: /root/db/swarm_memory.db

networks:
  swarm-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  swarm-memory:
    driver: local