name: Claude Auto-Fix

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'Task for Claude to perform'
        required: true
        type: string
      branch:
        description: 'Branch to work on'
        required: false
        default: 'claude-fixes'
        type: string
  push:
    paths:
      - '.github/claude-tasks.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create working branch
        run: |
          git checkout -b ${{ github.event.inputs.branch || 'claude-auto-fix' }}
          
      - name: Claude Code Implementation
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          mode: implement
          prompt: |
            Task: ${{ github.event.inputs.task || 'Check .github/claude-tasks.md for tasks' }}
            
            Please implement the requested changes following these guidelines:
            - Follow existing code style and conventions
            - Add appropriate tests
            - Update documentation if needed
            - Ensure backward compatibility
            - Add comments for complex logic
          claude_args: |
            --temperature 0.2
            --max-tokens 8192
            
      - name: Commit changes
        run: |
          git config --local user.email "claude-bot@example.com"
          git config --local user.name "Claude Bot"
          git add -A
          git diff --staged --quiet || git commit -m "🤖 Claude: ${{ github.event.inputs.task || 'Auto-fixes' }}"
          
      - name: Push changes
        run: |
          git push origin ${{ github.event.inputs.branch || 'claude-auto-fix' }}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.inputs.branch || 'claude-auto-fix' }}
          title: "🤖 Claude: ${{ github.event.inputs.task || 'Auto-fixes' }}"
          body: |
            ## 🤖 Claude Code Auto-Implementation
            
            ### Task
            ${{ github.event.inputs.task || 'Automated fixes and improvements' }}
            
            ### Changes Made
            This PR was automatically generated by Claude Code Action.
            
            Please review the changes before merging.
            
            ---
            *Generated by [Claude Code Action](https://github.com/anthropics/claude-code-action)*
          labels: |
            claude-generated
            automated-pr
            needs-review