name: Claude Documentation Sync

on:
  push:
    branches: [main, master]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.py'
      - '**/*.go'
      - '**/*.java'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Claude Documentation Generator
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          mode: docs
          prompt: |
            Analyze the codebase and:
            1. Update API documentation
            2. Generate/update README sections
            3. Create code examples
            4. Document complex functions
            5. Update changelog if needed
            
            Maintain existing documentation style and format.
          claude_args: |
            --temperature 0.1
            --max-tokens 8192
            
      - name: Commit documentation updates
        run: |
          git config --local user.email "claude-bot@example.com"
          git config --local user.name "Claude Documentation Bot"
          git add -A
          if git diff --staged --quiet; then
            echo "No documentation changes needed"
          else
            git commit -m "📚 Update documentation [skip ci]"
            git push
          fi